server:
  port: 8082

spring:
  application:
    name: mcp-server-demo
  ai:
    mcp:
      server:
        name: mcp-server-demo
        version: 1.0.0
        type: SYNC # Recommended for reactive applications
        instructions: "这个mcp server可以提供用户查询MSC商品信息"
        sse-message-endpoint: /mcp/message
        stdio: false
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true

